export const authTypes = {
  CHECKING_FINISH: '[AUTH] FINISH CHECKING LOGIN STATE',
  START_LOGIN: '[AUTH] START LOGIN',
  LOGIN: '[AUTH] LOGIN',
  START_REGISTER: '[AUTH] START REGISTER',
  START_TOKEN_RENEW: '[AUTH] START TOKEN RENEW',
  LOGOUT: '[AUTH] LOGOUT',
};
