export const calendarTypes = {
  ADD_NEW: '[CALENDAR] ADD NEW',
  SET_ACTIVE: '[CALENDAR] SET ACTIVE',
  CLEAR_ACTIVE: '[CALENDAR] CLEAR ACTIVE',
  UPDATE: '[CALENDAR] UPDATE',
  DELETE: '[CALENDAR] DELETE',
  LOAD: '[CALENDAR] LOAD',
  CLEAR_LOGOUT: '[CALENDAR] CLEAR LOGOUT',
};
